# Generated by Django 2.0.2 on 2018-03-28 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='user',
            new_name='users',
        ),
    ]
