# Generated by Django 2.0.2 on 2018-03-29 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20180328_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='users',
            new_name='user',
        ),
    ]
